services:
  backend:
    image: nikanostovan/notion_tasks_integration:latest
    container_name: notion_tasks_integration
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Database
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REFRESH_TOKEN_ID=${REFRESH_TOKEN_ID}
      - INTERNAL_INTEGRATION_SECRET=${INTERNAL_INTEGRATION_SECRET}
      - DATASOURCE_ID=${DATASOURCE_ID}
